In [20]:
# 🚀 Aula 2: Indexação e Fatiamento Avançado (Filtros Profissionais)
# Agora que você tem o estoque e os IDs, o gerente chega com um problema real de negócio: "Preciso rastrear apenas os produtos que estão com estoque crítico (abaixo de 5 unidades) ou faturando alto."

# Se você responder que vai usar um loop for e um if para varrer o array, você está reprovado na entrevista. No mercado, usamos Boolean Indexing (Indexação Booleana) ou Máscaras. É aqui que o NumPy brilha.

# Como funciona na prática?
# Quando você faz uma comparação direta em um array, o NumPy não compara o bloco inteiro; ele compara elemento por elemento e te devolve um array de True ou False.

# Python
# Simulando dados reais de vendas de 5 produtos

import numpy as np

vendas = np.array([120, 45, 90, 15, 200])

# Criando uma máscara para identificar vendas maiores que 50
mascara = vendas > 50
print(mascara) 
# Saída: [ True False  True False  True]

# Para extrair os valores reais, você passa essa máscara dentro dos colchetes do array original:

# Python
vendas_altas = vendas[mascara]
print(vendas_altas)
# Saída: [120  90 200]

[ True False  True False  True]
[120  90 200]


In [6]:
# Fatiamento de Matrizes (2D) - O terror dos candidatos
# No dia a dia, você lidará com tabelas (Matrizes). A sintaxe padrão é: array[linha, coluna].

# Python
# Uma matriz 3x3 representando: [ID do Produto, Qtd em Estoque, Preço]
dados_produtos = np.array([
    [101, 5, 25.00],
    [102, 0, 40.00],
    [103, 12, 15.50]
])

# Pegar APENAS os preços (todas as linhas, coluna de índice 2)
precos = dados_produtos[:, 2]
print(precos)
# Saída: [25.  40.  15.5]
# Nota de Mercado: O símbolo : significa "selecione tudo deste eixo". Então :, 2 significa "todas as linhas, coluna 2".

# ⚠️ Erro Clássico de Iniciante
# Tentar usar as palavras reservadas do Python and ou or para juntar múltiplos filtros no NumPy.

# Python
# ERRO CRÍTICO (Vai quebrar o código):
# vendas[(vendas > 50) and (vendas < 150)]
# No NumPy, para operações elemento por elemento, você obrigatoriamente deve usar os operadores bitwise: & para E e | para OU, sempre isolando as condições entre parênteses.

# Python
# CORRETO:
vendas[(vendas > 50) & (vendas < 150)]

[25.  40.  15.5]


array([120,  90])

In [22]:
# 🏋️ Exercício Prático 2
# Você recebeu um array com o faturamento diário de uma filial da empresa durante uma semana:

# Python
# faturamento_semana = np.array([2500, 1800, 4000, 900, 1200, 5000, 3100])
# Escreva o comando em NumPy para filtrar e retornar apenas os faturamentos que foram maiores que 2000 E menores que 4500.

faturamento_semana = np.array([2500, 1800, 4000, 900, 1200, 5000, 3100])
mascara = (faturamento_semana > 2000) & (faturamento_semana < 4500)
filtro_faturamento = faturamento_semana[mascara]
print("Filtro de faturamento entre 2000 e 4500:", filtro_faturamento)

Filtro de faturamento entre 2000 e 4500: [2500 4000 3100]


In [ ]:
# 📝 Resumo Rápido da Aula 2 (Folha de Consulta)
# & = Substitui o and para filtros elemento por elemento.

# | = Substitui o or para filtros elemento por elemento.

# Obrigatório: Sempre use (condicao1) & (condicao2). Sem os parênteses, o Python se perde na ordem de precedência matemática e quebra.