In [ ]:
%load_ext autoreload
%autoreload 2

In [1]:
# 🚀 Aula : O que é Broadcasting?

Quando você opera dois arrays de tamanhos diferentes, o NumPy "expande" o menor para combinar com o maior — sem copiar dados na memória. 

SyntaxError: invalid character '—' (U+2014) (1159853439.py, line 3)

In [1]:
import numpy as np

# Exemplo 1: Array + escalar (mais simples)
precos = np.array([100, 200, 300])
precos * 1.1
# NumPy expande o 1.1 para [1.1, 1.1, 1.1] internamente
# Resultado: [110. 220. 330.]

# Exemplo 2: Array 2D + Array 1D
vendas = np.array([
    [100, 200, 300],  # Loja A
    [400, 500, 600]   # Loja B
])
metas = np.array([150, 150, 150])

# NumPy expande metas para combinar com cada linha
resultado = vendas - metas
# [[-50,  50, 150],
#  [250, 350, 450]]

---

In [ ]:
## A regra do Broadcasting##
Para dois arrays operarem juntos, as dimensões precisam ser compatíveis da direita para a esquerda:

**vendas.shape → (2, 3)**
**metas.shape  →    (3,)   ← compatível (mesmo tamanho)**
**resultado    → (2, 3)    ✅**

**vendas.shape → (2, 3)**
**errado.shape →    (2,)   ← incompatível (3 ≠ 2)**
                          **❌ ValueError**

---

In [ ]:
## Exemplo de negócio real:

In [2]:
import numpy as np

# Faturamento de 3 lojas em 4 meses
faturamento = np.array([
    [10000, 12000, 11000, 13000],  # Loja A
    [8000,  9500,  8800,  9000],   # Loja B
    [15000, 14000, 16000, 15500]   # Loja C
])

# Meta mensal (uma por mês, vale pra todas as lojas)
meta_mensal = np.array([11000, 11000, 11000, 12000])

# Diferença de cada loja em relação à meta — broadcasting aqui
diferenca = faturamento - meta_mensal

print(diferenca)
# [[-1000,  1000,     0,  1000],  # Loja A
#  [-3000, -1500, -2200, -3000],  # Loja B
#  [ 4000,  3000,  5000,  3500]]  # Loja C

# Quais lojas bateram a meta em cada mês?
bateu_meta = faturamento >= meta_mensal
print(bateu_meta)

[[-1000  1000     0  1000]
 [-3000 -1500 -2200 -3000]
 [ 4000  3000  5000  3500]]
[[False  True  True  True]
 [False False False False]
 [ True  True  True  True]]


In [ ]:
## Erro clássico

In [ ]:
a = np.array([1, 2, 3])    # shape (3,)
b = np.array([1, 2])       # shape (2,)

a + b  # ❌ ValueError: operands could not be broadcast
       # 3 ≠ 2, não tem como expandir

---

In [3]:
## Exercicio Aula 5:

In [ ]:
import numpy as np

# Matriz de horas trabalhadas por 4 funcionários em 5 dias
horas = np.array([
    [8, 7, 9, 8, 8],   # Funcionário A
    [6, 8, 7, 9, 7],   # Funcionário B
    [9, 9, 8, 7, 9],   # Funcionário C
    [7, 6, 8, 8, 7]    # Funcionário D
])

# Valor da hora de cada funcionário (um por funcionário)
valor_hora = np.array([50, 45, 60, 40])

In [ ]:
**Missão:** Calcule o salário de cada funcionário por dia usando broadcasting. 
O resultado deve ser uma matriz (4, 5) onde cada elemento é horas * valor_hora do funcionário naquele dia.

In [ ]:
# Dica: valor_hora tem shape (4,)
# horas tem shape (4, 5)
# Para broadcastar corretamente, precisa reshape
valor_hora_reshape = valor_hora.reshape(4, 1)

In [12]:
import numpy as np

horas = np.array([
    [8, 7, 9, 8, 8],   # Funcionário A
    [6, 8, 7, 9, 7],   # Funcionário B
    [9, 9, 8, 7, 9],   # Funcionário C
    [7, 6, 8, 8, 7]    # Funcionário D
])

valor_hora = np.array([50, 45, 60, 40])

valor_hora_col = valor_hora.reshape(4, 1)
salario_por_dia = horas * valor_hora_col
print(salario_por_dia)



[[400 350 450 400 400]
 [270 360 315 405 315]
 [540 540 480 420 540]
 [280 240 320 320 280]]
